import { IconType } from "react-icons";
import {
  FaCode,
  FaDatabase,
  FaGithub,
  FaCogs,
  FaShieldAlt,
} from "react-icons/fa";
import {
  SiBlender,
  SiTypescript,
  SiJavascript,
  SiDjango,
  SiReact,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiHtml5,
  SiNodedotjs,
  SiPhp,
  SiVercel,
  SiNextdotjs,
  SiGit,
  SiUbuntu,
  SiYaml,
  SiTailwindcss,
  SiMarkdown,
  SiDocker,
  SiNginx,
  SiApache,
  SiArduino,
  SiNpm,
  SiPnpm,
  SiKicad,
  SiC,
  SiCplusplus,
  SiComposer,
  SiWolfram,
  SiJson,
  SiEslint,
  SiWordpress,
  SiFlask,
  SiOpenai,
  SiLinux,
  SiPython,
  SiGnubash,
} from "react-icons/si";
import { TbBrandPowershell } from "react-icons/tb";
import { DiJava } from "react-icons/di";

export interface TechStackElement {
  name: string;
  icon: IconType;
  color: string;
}

const names = [
  "Blender",
  "TypeScript",
  "JavaScript",
  "Django",
  "UPBGE",
  "React",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Bash",
  "HTML",
  "PowerShell",
  "SQL",
  "Node.js",
  "PHP",
  "Vercel",
  "Next.js",
  "Git",
  "Ubuntu",
  "YAML",
  "Tailwind CSS",
  "Markdown",
  "Docker",
  "NGINX",
  "Apache",
  "Zod",
  "Arduino",
  "Java",
  "GitHub",
  "npm",
  "pnpm",
  "KiCad",
  "C",
  "C++",
  "Composer",
  "Vivado",
  "MCUxpresso",
  "phpMyAdmin",
  "Wolfram",
  "Wolfram Language",
  "libGDX",
  "JSON",
  "Auth.js",
  "ESLint",
  "NumPy",
  "SciPy",
  "Matplotlib",
  "Wordpress",
  "Flask",
  "OpenAI",
  "Linux",
  "Better Auth",
  "Mathematica",
  "Python",
];

const iconMap: Record<string, IconType> = {
  Blender: SiBlender,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Django: SiDjango,
  UPBGE: FaCode,
  React: SiReact,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  SQLite: SiSqlite,
  Bash: SiGnubash,
  HTML: SiHtml5,
  PowerShell: TbBrandPowershell,
  SQL: FaDatabase,
  "Node.js": SiNodedotjs,
  PHP: SiPhp,
  Vercel: SiVercel,
  "Next.js": SiNextdotjs,
  Git: SiGit,
  Ubuntu: SiUbuntu,
  YAML: SiYaml,
  "Tailwind CSS": SiTailwindcss,
  Markdown: SiMarkdown,
  Docker: SiDocker,
  NGINX: SiNginx,
  Apache: SiApache,
  Zod: FaCogs,
  Arduino: SiArduino,
  Java: DiJava,
  GitHub: FaGithub,
  npm: SiNpm,
  pnpm: SiPnpm,
  KiCad: SiKicad,
  C: SiC,
  "C++": SiCplusplus,
  Composer: SiComposer,
  Vivado: FaCode,
  MCUxpresso: FaCogs,
  phpMyAdmin: FaDatabase,
  Wolfram: SiWolfram,
  "Wolfram Language": SiWolfram,
  libGDX: DiJava,
  JSON: SiJson,
  "Auth.js": FaShieldAlt,
  ESLint: SiEslint,
  NumPy: FaCode,
  SciPy: FaCode,
  Matplotlib: FaCode,
  Wordpress: SiWordpress,
  Flask: SiFlask,
  OpenAI: SiOpenai,
  Linux: SiLinux,
  "Better Auth": FaShieldAlt,
  Mathematica: SiWolfram,
  Python: SiPython,
};

const colorMap: Record<string, string> = {
  Blender: "#F5792A",
  TypeScript: "#3178C6",
  JavaScript: "#F7DF1E",
  Django: "#092E20",
  UPBGE: "#F5792A",
  React: "#61DAFB",
  PostgreSQL: "#336791",
  MySQL: "#00758F",
  SQLite: "#003B57",
  Bash: "#1EAC3F",
  HTML: "#E34F26",
  PowerShell: "#012456",
  SQL: "#F29111",
  "Node.js": "#43853D",
  PHP: "#777BB4",
  Vercel: "#000000",
  "Next.js": "#000000",
  Git: "#F05032",
  Ubuntu: "#E95420",
  YAML: "#CB171E",
  "Tailwind CSS": "#38B2AC",
  Markdown: "#000000",
  Docker: "#2496ED",
  NGINX: "#009639",
  Apache: "#D22128",
  Zod: "#7C3AED",
  Arduino: "#00979D",
  Java: "#007396",
  GitHub: "#181717",
  npm: "#CB3837",
  pnpm: "#F69220",
  KiCad: "#FF6A00",
  C: "#00599C",
  "C++": "#0052CC",
  Composer: "#8892BF",
  Vivado: "#FF6A00",
  MCUxpresso: "#0052CC",
  phpMyAdmin: "#2C3E50",
  Wolfram: "#FF6C00",
  "Wolfram Language": "#FF6C00",
  libGDX: "#2B3A42",
  JSON: "#292929",
  "Auth.js": "#21759B",
  ESLint: "#4B32C3",
  NumPy: "#013243",
  SciPy: "#8CAAE6",
  Matplotlib: "#11557C",
  Wordpress: "#21759B",
  Flask: "#000000",
  OpenAI: "#412991",
  Linux: "#000000",
  "Better Auth": "#0EA5A4",
  Mathematica: "#FF6C00",
  Python: "#3776AB",
};

export const techStack: readonly TechStackElement[] = names.map((n) => ({
  name: n,
  icon: iconMap[n] ?? FaCode,
  color: colorMap[n] ?? "#f83834",
}));

export function fetchStack(
  names: readonly string[],
): readonly TechStackElement[] {
  return names.map((n) => ({
    name: n,
    icon: iconMap[n] ?? FaCode,
    color: colorMap[n] ?? "#f83834",
  }));
}
