onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - es5-ext
  - msgpackr-extract
  - sharp
  - unrs-resolver

patchedDependencies:
  motion: patches/motion.patch
